-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias UserRequiredArguments =
    { username : String }


user :
    UserRequiredArguments
    -> SelectionSet decodesTo Api.Object.User
    -> SelectionSet decodesTo RootMutation
user requiredArgs____ object____ =
    Object.selectionForCompositeField "user" [ Argument.required "username" requiredArgs____.username Encode.string ] object____ identity
